# How to Test Hidden Promise-s Using Done or await

\- Promise-s are used all over Javascript
\- sometimes the Promise is not exposed out of the method-under-test (fire and forget)
\- such Promises can be tested using the Done function or `async` and `await`

In everyday work, we often need to deal with Promises ([MDN article](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Using_promises)). If the function we test is `async` i.e. returns a `Promise`, we can use `async` and `await` in our tests (see "How to Test Promise-s Using async and await").

When the function is not returning a `Promise` and not using the `async` keyword but is still relying on `Promises` we can not use Jasmine's async testing capabilities directly. There are two approaches for testing such functions/methods that "hide" their `Promise`-s:

- the `Done` function from Jasmine
- `async` and `await` with an assisting `Promise`

Let's start with the class that has this hidden-Promise method - the `ArticleDelete` class.

## The ArticleDelete class

What follows is a very simplified example of a class that handles deleting articles in a browser application. It will accept some input and make a request to a server API if conditions are met.

> For this lesson, the `delete` method is not `async`-chronous but still uses the `Promise` returning `ArticleAPI` and
> works with `.then` and `.catch` callbacks. This is the traditional [`Promise` chain flow](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Using_promises#chaining).

Run the code playground below and see the breakdown below.

## ArticleDelete class breakdown

The `ArticleDelete` class is relying on a `ArticleAPI` class to make a `DELETE /api/article/:id` call if conditions are met.

- `ArticleAPI` is a class that would implement the server API call. _It is empty as that's outside of the current lesson scope, and we'll be mocking its responses for the tests_
- `ArticleDelete` is the main class

  - ```js
    import { ArticleAPI } from './article-api.mjs';
    ```

    importing the ArticleAPI dependency from the adjacent module in the current folder `article-api.mjs`

  - ```js
    export class ArticleDelete {
    ```

    exporting the class to be used in other modules

  - ```js
      /** @type {ArticleAPI} */
      articleAPI;
      deleteResult;

      /**
       * @param { ArticleAPI } article the article api
       */
      constructor(articleApi) {
        this.articleAPI = articleApi;
      }
    ```

    declaring the `articleAPI` class instance property and populating it when an instance of the class gets constructed. In other words,  constructing an instance of the `ArticleDelete` class will require an instance of the `ArticleAPI` class. Also declaring `deleteResult` to be used in the `delete` method.

  - ```js
    delete(a) {
      // ...
    }
    ```

    notice the method is not preceded by the `await` keyword and we'll see below it does not return a `Promise`. That means that `await`-ing it in a test will not do us any good as the `await` will only wait for a `Promise`.

  - ```js
    this.deleteResult = undefined;
    ```

    resets the `deleteResult` at the beginning of an article delete process. That class property will get used to communicating the result with the human user e.g. by showing it in a `<span>`.

  - ```js
    if (a != null && a.id != null) {
      // ... see below
    } else {
      this.deleteResult = 'no article to delete';
    }

    when there's an article with an `id` passed in it will continue and delete it, and if not, will return an explanatory string

  - ```js
    this.articleAPI
      .delete(a.id)
      .then(() => (this.deleteResult = `article deleted: "${a.title}"`))
      .catch(/*...see below*/);
    ```

    calls the ArticleAPI `delete` method and attaches a `then` callback on the success i.e. `Promise` resolved. It fills in the `deleteResult`

  - ```js
    (e) => {
      if (e && e.status === 404) {
        this.deleteResult = `It looks like article "${a.title}" has already been deleted`;
      } else {
        this.deleteResult = `Unknown error trying to delete "${a.title}". Please try again.`;
      }
    }
    ```

    The `catch` callback is called if the `delete` method returns a promise that gets rejected. `e` is the rejection data. It handles 2 cases:

    - when the response has a status of `404 Not found` and sets the `deleteResult` to "already deleted"
    - otherwise, sets the `deleteResult` to "unknown - please try again"

## Test breakdown

Looking at the `spec/article-delete.spec.mjs` file we have:

- ```js
  import { ArticleDelete } from '../__src__/article-delete.mjs';

  describe('ArticleDelete', () => {
  ```

  we start with `import`ing the `ArticleDelete` class and declaring a test suite for it `describe('ArticleDelete', () => {`

- ```js
  let article;
  let articleAPI;

  beforeEach(() => {
    articleAPI = jasmine.createSpyObj('article API', ['delete']);
    article = new ArticleDelete(articleAPI);
  });
  ```

  knowing that we need an instance of the `ArticleAPI` we create a spy object with a spy on the `delete` method as that's the only method we use in the logic of the `ArticleDelete` class. Then in the next line, we instantiate an `ArticleDelete` instance. These two instances will get renewed `beforeEach` test so that each test executes in isolation from the others and no one test influences the others.

### Green path breakdown

In the test case `should call the articleAPI delete and return the deleted article title` we focus on the so-called "green path" test AKA "happy path" [wiki article](https://en.wikipedia.org/wiki/Happy_path). That is testing for the case that the method receives what it expects and works as intended.

- ```js
  it(`should call the articleAPI delete and return the deleted article title`, (done) => {
  ```

  notice the second parameter of `it` is not an `async` function. It takes the `done` parameter which comes from Jasmine and is a function that Jasmine will expect to get called before it considers a test finished. [Jasmine docs](https://jasmine.github.io/tutorials/async#callbacks) and [Jasmine types](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/39c90291062b269d2c4f19ca7d65369c210696aa/types/jasmine/index.d.ts#L169-L174)

- ```js
  // arrange
  articleAPI.delete.and.returnValue(Promise.resolve({id: 1}));
  ```

  using the mocking capabilities, we make sure that when the `delete` method of the `ArticleAPI` gets called, it returns a `Promise`. `Promise.resolve` returns a `Promise` that is resolved with the specified result - in this case `{id: 1}`.

- ```js
  // act
  article.delete({ id: 1, title: 'the first article' });
  ```

  then, we call the `delete` method. Since we can not `await` its response to get resolved we'll start a timeout below

- ```js
  // assert
  setTimeout(() => {
    expect(article.deleteResult).toEqual('It looks like article "the first article" has already been deleted');
    done();
  });
  ```

  we need the assertion to be executed after the "hidden" promise finishes. So we use `setTimeout`. It schedules the assertion in the next available event loop cycle ([event loop video](https://www.youtube.com/watch?v=8aGhZQkoFbQ&vl=en)), which ensures the `Promise` callback was executed before the expression `expect(article.deleteResult)....` gets called.

  >Experiment: try commenting out the `setTimeout(() => {` and its closing brackets `});` and see the test failing.

### 404 error test breakdown

In the test case `when the articleAPI delete returns status 404 it should return - already been deleted`, we'll make sure the behavior of the `ArticleDelete.delete` method is as expected for the case that a `404 Not found` is returned from the server.

- ```js
  it(`when the articleAPI delete returns status 404 it should return - already been deleted`, (done) => {
  ```

  using `it` with the `done` function parameter and not `async`

- ```js
  // arrange
  articleAPI.delete.and.returnValue(Promise.reject({status: 404, message: 'not found'}));
  ```

  using the mocking capabilities, we make sure that when the `delete` method of the `ArticleAPI` gets called, it returns a `Promise`. `Promise.reject` returns a `Promise` that is rejected with the specified result - in this case `{status: 404, message: 'not found'}`.

  _Note: This is just an example of how a rejected Promise might look like ([axios](https://axios-http.com/docs/handling_errors)). Depending on the specific API or library used the rejection might not happen on a 404_

- ```js
  // act
  article.delete({ id: 1, title: 'the first article' });
  ```

  then, we call the `delete` method.

- ```js
  // assert
  setTimeout(() => {
    expect(article.deleteResult).toEqual('It looks like article "the first article" has already been deleted');
    done();
  });
  ```

  finally, we assert that the `delete` gets called and the `result` is as expected for the "404" case. This is using the `setTimeout` to make sure the `expect`-ation call is after the `.catch` callback from `ArticleDelete` line#23.

## Exercise

For this exercise, we'll focus on `src/article-create.mjs` in the code playground below. The `ArticleCreate` class is very similar to `ArticleDelete`, with the main difference being the `create` method:

- ```js
  create(title, content) {
    this.createResult = undefined;
    if (typeof title === 'string' && typeof content === 'string') {
      this.articleAPI
        .create(title, content)
        .then(() => (this.createResult = `article created: "${title}" with content "${content}"`))
        .catch((e) => {
          if (e && e.status === 409) {
            this.createResult = `it appears that an article with that title "${title}" already exists`;
          } else {
            this.createResult = `failed creating article ${title} - please try again later`;
          }
        });
    } else {
      this.createResult = `expected string title and content but received title: "${title}" content: "${content}"`;
    }
  }
  ```

  - it takes two parameters: `title` and `content` to create the article, and it invokes the `ArticleAPI`'s `create` method.
  - the `createResult` property is used to convey the result: success or an error
  - in the case of a status [409 Conflict](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/409), it advises there is an article with such a title already
  - there is also the quick fail when the title or content are missing or not a string *Notice the Promise returning (AKA async) method does not get called for this case*

Let's create the four specs for the above logic:

- when called with title and content, it invokes the `ArticleAPI`'s method `create`
- when the API returns a 409 Conflict, it should advise the caller such a title already exists
- when the API returns a generic error, it should advise the caller about the unknown error
- when called without a title or content, it returns an error explanation.

>Note: the tests for `ArticleDelete` are part of the code playground too.

>When `done` is not called tests timeout! If you opt to use the assisting Promise - remove `done` from the parameter list of the `it` callback function.

Show Hint for `should call the articleAPI create and return the created article title and content`

```js
it(`should call the articleAPI create and return the created article title and content`, (done) => {
  // arrange
  articleAPI.create.and.returnValue(Promise.resolve({ id: 1 }));
  // act
  article.create('title', 'content');
  // assert
  setTimeout(() => {
    expect(articleAPI.create).toHaveBeenCalledOnceWith('title', 'content');
    expect(article.createResult).toEqual('article created: "title" with content "content"');
    done();
  });
});
```

Show Hint for `when the API returns a 409 Conflict it should advise caller such a title already exists`

```js
it(`when the API returns a 409 Conflict it should advise caller such a title already exists`, (done) => {
  // arrange
  articleAPI.create.and.returnValue(Promise.reject({ status: 409 }));
  // act
  article.create('title', 'content');
  // assert
  setTimeout(() => {
    expect(articleAPI.create).toHaveBeenCalledOnceWith('title', 'content');
    expect(article.createResult).toEqual(`it appears that an article with that title "title" already exists`);
    done();
  });
});
```

Show Hint for `when the API returns an error it should advise the caller of unknown error`

```js
it(`when the API returns an error it should advise caller of unknown error`, (done) => {
  // arrange
  articleAPI.create.and.returnValue(Promise.reject({ status: 500 }));
  // act
  article.create('title', 'content');
  // assert
  setTimeout(() => {
    expect(articleAPI.create).toHaveBeenCalledOnceWith('title', 'content');
    expect(article.createResult).toEqual(`failed creating article title - please try again later`);
    done();
  });
});
```

Show Hint for `should return what was expected and what was received when missing parameters or not string`

```js
it(`should return what was expected and what was received when missing parameters or not string`, () => {
  // arrange
  // act
  article.create('');
  // assert
  expect(article.createResult).toEqual(
    `expected string title and content but received title: "" content: "undefined"`
  );
});
```
