# How to Test Node.js API Logic

We'll take a look at the back-end side and how to test an implementation of an `ArticleApiController` with asynchronous `get` and `delete` endpoints.

[expectAsync, Nodejs, api]

One way of handling the API calls to the backend is in a class dedicated to a resource. In today's lesson, we'll look at one such case. The `ArticleApiController` will implement a `get` method that provided an id returns the corresponding article. And a `delete` method that provided an `id` and an `etag` deletes the corresponding article.

Explore the code in the next code playground and let's break it down after.

// code

## The class breakdown - ArticleApiController

If we are using a web framework like [express.js](https://expressjs.com/) it handles a lot of the HTTP stuff for us. We are left with the need to implement our logic. The `ArticleApiController` is this logic. It exposes a method `get` that allows clients to request an article by providing an `id`. Looking at `src/article-controller.js` :

- ```js
  db;

  constructor(db) {
    this.db = db;
  }
  ```

  The `ArticleApiController` expects to get a `db` which would allow connecting and manipulating a database of some sort. This is a dependency and we'll mock it for the test so we won't get into further details here. For the example, it's assumed to be a [mongodb connection](https://docs.mongodb.com/drivers/node/current/)

- ```js
  async get(id) {
    try {
      const a = await this.db.collection('Article').findOne({ id: id });
      return a;
    } catch (e) {
      throw { status: 'not found', message: `Article with id "${id}" was not found.` };
    }
  }
  ```

  This `async`-chronous method will return the article if found and will throw an error otherwise. The `try catch` wraps the call to the database and makes sure that if the connection fails or the article is not found or any other error occurs it is caught and an error with status and a message is thrown up. That error will presumably cause a `4xx` status response to be returned to the client over HTTP.

  That logic will allow us to showcase `expectAsync`.

- ```js
  this.db.collection('Article').findOne({ id: id });
  ```

  This is an example of using a [mongodb collection](https://mongodb.github.io/node-mongodb-native/4.1/classes/Collection.html) to fetch a single entity [article](https://mongodb.github.io/node-mongodb-native/4.1/classes/Collection.html#findOne)

## Tests breakdown

There are two tests in this example plus a `beforeEach` that will set up each test.

- ```js
  let db;
  let articleCollection;
  let articleController;

  beforeEach(() => {
    articleCollection = jasmine.createSpyObj('collection', ['findOne', 'delete']);
    db = jasmine.createSpyObj('db mock', {
      collection: articleCollection,
    });
    articleController = new ArticleApiController(db);
  });
  ```

  Before each test, the logic above will run and create an instance of `ArticleApiController`. That will require an instance of `db` - the database access abstraction mock. The `db` exposes a method `collection` so we create the spy object with a `collection` method mock which returns the `articleCollection` spy object. The `articleCollection` is a spy object with spies on two methods - `findOne` and `delete`.

- ```js
  describe('when get called', () => {
  ```

  Notice we create a sub-suite `when get called` which will complement the `ArticleApiController` main suite. Each test from the sub-suite will get reported under the sub-suite which is reported under the main suite. That will come in handy later when we add tests for `delete` method (which is not included in this example for simplicity).

- ```js
  it('should search the article collection and resolve with the article when found', async () => {
    // arrange
    articleCollection.findOne.and.returnValue(
      Promise.resolve({ id: 1, title: 'Article', content: 'The lorem ipsum ...' })
    );
    // act
    const a = await articleController.get(1);
    // assert
    expect(articleCollection.findOne).toHaveBeenCalledOnceWith({ id: 1 });
    expect(a).toEqual(jasmine.objectContaining({ id: 1 }));
  });
  ```

  The above is an `async`-hronous test case that verifies the expected method `findOne` has been called and the final response returned is as expected:

  - It provides a response for the `findOne` method - a `Promise` immediately resolving to an object with an `id`.
  - It calls the `get` method giving a `1` for the `id` parameter.
  - It asserts that the `db` method `findOne` has been called with the expected filter `{ id: 1}`.
  - It asserts that the response is an object that contains a property of `id` that equals `1`.

  This is the "green" path - the input is as expected and the output is the article.

- ```js
  it('should search the article collection and reject with an object with status and message', async () => {
    // arrange
    articleCollection.findOne.and.returnValue(Promise.reject({ error: 'eee' }));
    // act
    // assert
    await expectAsync(articleController.get(1)).toBeRejectedWith({
      status: 'not found',
      message: 'Article with id "1" was not found.',
    });
  });
  ```

  The above is an `async`-hronous test case that verifies the `Promise` returned from the `get` method is rejected with the expected error status object:

  - It provides a response to the `findOne` method - a `Promise` immediately rejecting with an error. Since there is no logic discerning different kinds of errors it doesn't matter what the error is.
  - It uses and `await`-s the `expectAsync` function from [Jasmine](https://jasmine.github.io/api/3.9/global.html#expectAsync). It allows us to verify that a `Promise` is resolved or rejected with a specific value. In this case, we use the `toBeRejectedWith` to ensure that indeed the `articleController.get`'s response `Promise` rejects with the status and message as expected.

  This is the expected failing case.

  Notice that `// act` and `// assert` are next to one another. That's to denote that on the next line we act but also assert. The same logic could also separate the act from assert like this:

  ```js
  // act
  const a = articleController.get(1);
  // assert
  await expectAsync(a).toBeRejectedWith({
    status: 'not found',
    message: 'Article with id "1" was not found.',
  });
  ```

## Exercise

For the exercise let's try and test a `delete` method that is part of the `src/article-controller.js` file in the code playground below. The method accepts an `id` and a `etag` and checks if the [etag](https://en.wikipedia.org/wiki/HTTP_ETag) matches with the article found in the database:

- If it matches - delete is a go and proceeds.
- If it does not match the method throw a status object.
- If the article is not found in the database the error caught is re-thrown. That's the error from the `get` method.
- If the article delete fails a `delete failed` status object is thrown.

Use the playground below to write a test case for each of the cases enumerated above. Replace the lines `pending(...)` with your code.

// code

Show Hint for 'with an id and matching etag to version should delete the article'

````js
it('with an id and matching etag to version should delete the article', async () => {
  // arrange
  articleCollection.findOne.and.returnValue(Promise.resolve({ id: 1, version: '2' }));
  articleCollection.delete.and.returnValue(Promise.resolve({ id: 1, version: '2' }));
  // act
  const a = await articleController.delete(1, '2');
  // assert
  expect(articleCollection.delete).toHaveBeenCalledOnceWith({ id: 1 });
});
````

Show Hint for 'with an id and mismatching etag to version should not delete the article and reject with a status object'

```js
it('with an id and mismatching etag to version should not delete the article and reject with a status object', async () => {
  // arrange
  articleCollection.findOne.and.returnValue(Promise.resolve({ id: 1, version: '3' }));
  articleCollection.delete.and.returnValue(Promise.resolve({ id: 1, version: '2' }));
  // act
  const deletePromise = articleController.delete(1, '2');
  // assert
  await expectAsync(deletePromise).toBeRejectedWith({
    status: 'version mismatch',
    message: 'Article with id "1" seems to have been updated and client and server versions do not match.',
  });
  expect(articleCollection.delete).not.toHaveBeenCalled();
});
```

Show Hint for 'and get article fails it should reject with the same error'
```js
it('and get article fails it should reject with the same error', async () => {
  // arrange
  articleCollection.findOne.and.returnValue(Promise.reject({ status: 'not found' }));
  // act
  // assert
  await expectAsync(articleController.delete(1, '2')).toBeRejectedWith({
    status: 'not found',
    message: 'Article with id "1" was not found.'
  });
  expect(articleCollection.delete).not.toHaveBeenCalled();
})
```

Show Hint for 'and delete article in the DB fails it should reject with status object error'

```js
it('and delete article in the DB fails it should reject with status object error', async () => {
  // arrange
  articleCollection.findOne.and.returnValue(Promise.resolve({ id: 1, version: '3' }));
  articleCollection.delete.and.returnValue(Promise.reject({}));
  // act
  // assert
  await expectAsync(articleController.delete(1, '3')).toBeRejectedWith({
    status: 'delete failed',
    message: `Article with id "1" could not be deleted.`,
  });
});
```
